export const STORE_RESTAURANT_INITIAL_LIST_LOAD = 'STORE_RESTAURANT_INITIAL_LIST_LOAD';
export const UPDATE_RESTAURANT_FILTERED_LIST = 'UPDATE_RESTAURANT_FILTERED_LIST';
export const UPDATE_SELECTED_FILTER_OPTION = 'UPDATE_SELECTED_FILTER_OPTION';
export const UPDATE_FILTER_OPTIONS_LIST = 'UPDATE_FILTER_OPTIONS_LIST';
