// filter / sorter
export const UPDATE_FILTER_OPTIONS_LIST = 'UPDATE_FILTER_OPTIONS_LIST';
export const UPDATE_SELECTED_FILTER_OPTION = 'UPDATE_SELECTED_FILTER_OPTION';

// list
export const UPDATE_RESTAURANT_FILTERED_LIST = 'UPDATE_RESTAURANT_FILTERED_LIST';
export const STORE_RESTAURANT_INITIAL_LIST_LOAD = 'STORE_RESTAURANT_INITIAL_LIST_LOAD';

// details
export const STORE_LOADED_RESTAURANT_DETAILS = 'STORE_LOADED_RESTAURANT_DETAILS';
export const CLEARS_LOADED_RESTAURANT_DETAILS = 'CLEARS_LOADED_RESTAURANT_DETAILS';
